### ISSUE TITLE
The day I needed this it appeared! 

### ISSUE THREAD

**Issue by spacewalkingninja** [ismail-amouma/MEXC_Future_Order_API_Maintenance_Bypass#1]
Literally spent the night digging around, found that sad thingamajig https://maintenancebypass.com/ but you saved the night hehe! Thanks!!! Will post your work on reddit right away! 
ninja out

**Comment by ismail-amouma** [comment]
Glad it helped you out, @spacewalkingninja! Thanks for sharing the project on Reddit—really appreciate it! 😊
