### ISSUE TITLE
{'success': False, 'code': 602, 'message': 'Signature verification failed!'}

### ISSUE THREAD

**Issue by ilovehcking** [ismail-amouma/MEXC_Future_Order_API_Maintenance_Bypass#3]
i changed the script to everything right i always get this error 

{'success': False, 'code': 602, 'message': 'Signature verification failed!'}

**Comment by ismail-amouma** [comment]
whats changes did u made ?

**Comment by ilovehcking** [comment]
import hashlib
import json
import time
from curl_cffi import requests


import requests
import math
import pandas as pd
import pandas_ta as ta
import time
from termcolor import colored
import threading
from datetime import datetime







KLINE_API_URL = "https://contract.mexc.com/api/v1/contract/kline/BTC_USDT"

def get_kline_data(symbol="BTC_USDT", interval="Min1", limit=50):
    params = {
        "symbol": symbol,
        "interval": interval,
        "limit": limit
    }
    response = requests.get(KLINE_API_URL, params=params)
    data = response.json()
    
    if not data['success']:
        raise Exception("API call failed")

    df = pd.DataFrame({
        'timestamp': data['data']['time'],
        'open': data['data']['open'],
        'high': data['data']['high'],
        'low': data['data']['low'],
        'close': data['data']['close'],
        'volume': data['data']['vol']
    })
    
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='s')
    return df




df = get_kline_data(symbol="BTC_USDT", interval="Min1", limit=50)

latestPrice = df['close'].iloc[-1]

print(latestPrice)







def md5(value):
    return hashlib.md5(value.encode('utf-8')).hexdigest()

def mexc_crypto(key, obj):
    date_now = str(int(time.time() * 1000))  
    g = md5(key + date_now)[7:] 
    s = json.dumps(obj, separators=(',', ':'))  
    sign = md5(date_now + s + g)  
    print(sign + "-------" + date_now)
    return {'time': date_now, 'sign': sign}

def place_order(key, obj, url):
    signature = mexc_crypto(key, obj)
    headers = {
        'Content-Type': 'application/json',
        'x-mxc-sign': signature['sign'],
        'x-mxc-nonce': signature['time'],
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
        'Authorization': key
    }
    response = requests.post(url, headers=headers, json=obj)
    return response.json()

key = 'WEB...' #i added my WEBkey from the cookies after i logged in


obj = { 
    "symbol": "BTC_USDT", 
    "side": 1, 
    "openType": 1, 
    "type": "1", 
    "vol": 1, 
    "leverage": 1, 
    "price": latestPrice, 
    "priceProtect": "0",
}

url = 'https://futures.mexc.com/api/v1/private/order/create'  

response = place_order(key, obj, url)
print(response)

**Comment by ismail-amouma** [comment]
what's the type of `latestPrice ` ?

**Comment by ilovehcking** [comment]
i think its a float

**Comment by ismail-amouma** [comment]
did you try the code without the modifications ? they might change the signature algorithm

**Comment by ilovehcking** [comment]
you mean change the price back to "price": 2.5,

**Comment by ilovehcking** [comment]
still the same error {'success': False, 'code': 602, 'message': 'Signature verification failed!'}
i think they changed there signature algorithm

**Comment by ismail-amouma** [comment]
Yab probably

**Comment by ilovehcking** [comment]
Okay, do you think you'll continue maintaining the project, or will you leave it as it is?

**Comment by ilovehcking** [comment]
i think after it got posted on reddit they fixed it

**Comment by ismail-amouma** [comment]
if i find some time i will try to maintain it

**Comment by Lenn007xD** [comment]
Me too

**Comment by ismail-amouma** [comment]
Okay, someone sent 7 USDT to this account '44435178' so I could make a browser request and observe any changes. I don’t usually deal with crypto, and I don't own any. Originally, this was a project from a freelance client.

**Comment by ilovehcking** [comment]
i will send you 10 if you do it right now

**Comment by ismail-amouma** [comment]
Man i will not take anything of that money lol i just need to send make order throw browser to see the request

**Comment by ilovehcking** [comment]
ok send me your mexc id

**Comment by ilovehcking** [comment]
ok i will send it right now, can you send back after you got the request

**Comment by ismail-amouma** [comment]
ok

**Comment by ilovehcking** [comment]
send

**Comment by ismail-amouma** [comment]
![image](https://github.com/user-attachments/assets/93d584b3-203d-4f6a-9cb8-f8eb94a0b7a2)
Yap i got it send me ur uid so i return ur money Send me message in Telegram https://t.me/pip_install_life to send u new code if i put it here it will get change again .

**Comment by Lenn007xD** [comment]
Is there a possibility that I can also get the code?
